// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/etu.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DisabledReason enum for account disable reasons
type DisabledReason int32

const (
	DisabledReason_DISABLED_REASON_UNSPECIFIED      DisabledReason = 0
	DisabledReason_DISABLED_REASON_TERMS_VIOLATION  DisabledReason = 1
	DisabledReason_DISABLED_REASON_SECURITY_CONCERN DisabledReason = 2
	DisabledReason_DISABLED_REASON_USER_REQUEST     DisabledReason = 3
	DisabledReason_DISABLED_REASON_PAYMENT_ISSUE    DisabledReason = 4
	DisabledReason_DISABLED_REASON_OTHER            DisabledReason = 5
)

// Enum value maps for DisabledReason.
var (
	DisabledReason_name = map[int32]string{
		0: "DISABLED_REASON_UNSPECIFIED",
		1: "DISABLED_REASON_TERMS_VIOLATION",
		2: "DISABLED_REASON_SECURITY_CONCERN",
		3: "DISABLED_REASON_USER_REQUEST",
		4: "DISABLED_REASON_PAYMENT_ISSUE",
		5: "DISABLED_REASON_OTHER",
	}
	DisabledReason_value = map[string]int32{
		"DISABLED_REASON_UNSPECIFIED":      0,
		"DISABLED_REASON_TERMS_VIOLATION":  1,
		"DISABLED_REASON_SECURITY_CONCERN": 2,
		"DISABLED_REASON_USER_REQUEST":     3,
		"DISABLED_REASON_PAYMENT_ISSUE":    4,
		"DISABLED_REASON_OTHER":            5,
	}
)

func (x DisabledReason) Enum() *DisabledReason {
	p := new(DisabledReason)
	*p = x
	return p
}

func (x DisabledReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DisabledReason) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_etu_proto_enumTypes[0].Descriptor()
}

func (DisabledReason) Type() protoreflect.EnumType {
	return &file_proto_etu_proto_enumTypes[0]
}

func (x DisabledReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DisabledReason.Descriptor instead.
func (DisabledReason) EnumDescriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{0}
}

// ImageUpload message for uploading images (client -> server)
type ImageUpload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageUpload) Reset() {
	*x = ImageUpload{}
	mi := &file_proto_etu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageUpload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageUpload) ProtoMessage() {}

func (x *ImageUpload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageUpload.ProtoReflect.Descriptor instead.
func (*ImageUpload) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{0}
}

func (x *ImageUpload) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ImageUpload) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

// AudioUpload message for uploading audio files (client -> server)
type AudioUpload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioUpload) Reset() {
	*x = AudioUpload{}
	mi := &file_proto_etu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioUpload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioUpload) ProtoMessage() {}

func (x *AudioUpload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioUpload.ProtoReflect.Descriptor instead.
func (*AudioUpload) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{1}
}

func (x *AudioUpload) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AudioUpload) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

// NoteImage message for images attached to notes (server -> client)
type NoteImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	ExtractedText string                 `protobuf:"bytes,3,opt,name=extracted_text,json=extractedText,proto3" json:"extracted_text,omitempty"`
	MimeType      string                 `protobuf:"bytes,4,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteImage) Reset() {
	*x = NoteImage{}
	mi := &file_proto_etu_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteImage) ProtoMessage() {}

func (x *NoteImage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteImage.ProtoReflect.Descriptor instead.
func (*NoteImage) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{2}
}

func (x *NoteImage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NoteImage) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *NoteImage) GetExtractedText() string {
	if x != nil {
		return x.ExtractedText
	}
	return ""
}

func (x *NoteImage) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *NoteImage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// NoteAudio message for audio files attached to notes (server -> client)
type NoteAudio struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url             string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	TranscribedText string                 `protobuf:"bytes,3,opt,name=transcribed_text,json=transcribedText,proto3" json:"transcribed_text,omitempty"`
	MimeType        string                 `protobuf:"bytes,4,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NoteAudio) Reset() {
	*x = NoteAudio{}
	mi := &file_proto_etu_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteAudio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteAudio) ProtoMessage() {}

func (x *NoteAudio) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteAudio.ProtoReflect.Descriptor instead.
func (*NoteAudio) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{3}
}

func (x *NoteAudio) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NoteAudio) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *NoteAudio) GetTranscribedText() string {
	if x != nil {
		return x.TranscribedText
	}
	return ""
}

func (x *NoteAudio) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *NoteAudio) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Note message
type Note struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Images        []*NoteImage           `protobuf:"bytes,6,rep,name=images,proto3" json:"images,omitempty"`
	Audios        []*NoteAudio           `protobuf:"bytes,7,rep,name=audios,proto3" json:"audios,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Note) Reset() {
	*x = Note{}
	mi := &file_proto_etu_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Note) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Note) ProtoMessage() {}

func (x *Note) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Note.ProtoReflect.Descriptor instead.
func (*Note) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{4}
}

func (x *Note) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Note) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Note) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Note) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Note) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Note) GetImages() []*NoteImage {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Note) GetAudios() []*NoteAudio {
	if x != nil {
		return x.Audios
	}
	return nil
}

// Tag message
type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_proto_etu_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{5}
}

func (x *Tag) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tag) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Tag) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// User message
type User struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email              string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name               *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Image              *string                `protobuf:"bytes,4,opt,name=image,proto3,oneof" json:"image,omitempty"`
	SubscriptionStatus string                 `protobuf:"bytes,5,opt,name=subscription_status,json=subscriptionStatus,proto3" json:"subscription_status,omitempty"`
	SubscriptionEnd    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=subscription_end,json=subscriptionEnd,proto3,oneof" json:"subscription_end,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StripeCustomerId   *string                `protobuf:"bytes,8,opt,name=stripe_customer_id,json=stripeCustomerId,proto3,oneof" json:"stripe_customer_id,omitempty"`
	NotionKey          *string                `protobuf:"bytes,9,opt,name=notion_key,json=notionKey,proto3,oneof" json:"notion_key,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Disabled           bool                   `protobuf:"varint,12,opt,name=disabled,proto3" json:"disabled,omitempty"`
	DisabledReason     *DisabledReason        `protobuf:"varint,13,opt,name=disabled_reason,json=disabledReason,proto3,enum=etu.DisabledReason,oneof" json:"disabled_reason,omitempty"`
	LockedUntil        *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=locked_until,json=lockedUntil,proto3,oneof" json:"locked_until,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_etu_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{6}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *User) GetImage() string {
	if x != nil && x.Image != nil {
		return *x.Image
	}
	return ""
}

func (x *User) GetSubscriptionStatus() string {
	if x != nil {
		return x.SubscriptionStatus
	}
	return ""
}

func (x *User) GetSubscriptionEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.SubscriptionEnd
	}
	return nil
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetStripeCustomerId() string {
	if x != nil && x.StripeCustomerId != nil {
		return *x.StripeCustomerId
	}
	return ""
}

func (x *User) GetNotionKey() string {
	if x != nil && x.NotionKey != nil {
		return *x.NotionKey
	}
	return ""
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *User) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *User) GetDisabledReason() DisabledReason {
	if x != nil && x.DisabledReason != nil {
		return *x.DisabledReason
	}
	return DisabledReason_DISABLED_REASON_UNSPECIFIED
}

func (x *User) GetLockedUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.LockedUntil
	}
	return nil
}

// API Key message
type ApiKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	KeyPrefix     string                 `protobuf:"bytes,3,opt,name=key_prefix,json=keyPrefix,proto3" json:"key_prefix,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsed      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_used,json=lastUsed,proto3,oneof" json:"last_used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiKey) Reset() {
	*x = ApiKey{}
	mi := &file_proto_etu_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKey) ProtoMessage() {}

func (x *ApiKey) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKey.ProtoReflect.Descriptor instead.
func (*ApiKey) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{7}
}

func (x *ApiKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApiKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApiKey) GetKeyPrefix() string {
	if x != nil {
		return x.KeyPrefix
	}
	return ""
}

func (x *ApiKey) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ApiKey) GetLastUsed() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsed
	}
	return nil
}

type ListNotesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Required for auth context
	Search        string                 `protobuf:"bytes,2,opt,name=search,proto3" json:"search,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	StartDate     string                 `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // ISO 8601 format
	EndDate       string                 `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`       // ISO 8601 format
	Limit         int32                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,7,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotesRequest) Reset() {
	*x = ListNotesRequest{}
	mi := &file_proto_etu_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotesRequest) ProtoMessage() {}

func (x *ListNotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotesRequest.ProtoReflect.Descriptor instead.
func (*ListNotesRequest) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{8}
}

func (x *ListNotesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListNotesRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListNotesRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ListNotesRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *ListNotesRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *ListNotesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListNotesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListNotesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notes         []*Note                `protobuf:"bytes,1,rep,name=notes,proto3" json:"notes,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotesResponse) Reset() {
	*x = ListNotesResponse{}
	mi := &file_proto_etu_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotesResponse) ProtoMessage() {}

func (x *ListNotesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotesResponse.ProtoReflect.Descriptor instead.
func (*ListNotesResponse) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{9}
}

func (x *ListNotesResponse) GetNotes() []*Note {
	if x != nil {
		return x.Notes
	}
	return nil
}

func (x *ListNotesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListNotesResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListNotesResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type CreateNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Required for auth context
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Images        []*ImageUpload         `protobuf:"bytes,4,rep,name=images,proto3" json:"images,omitempty"`
	Audios        []*AudioUpload         `protobuf:"bytes,5,rep,name=audios,proto3" json:"audios,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNoteRequest) Reset() {
	*x = CreateNoteRequest{}
	mi := &file_proto_etu_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNoteRequest) ProtoMessage() {}

func (x *CreateNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNoteRequest.ProtoReflect.Descriptor instead.
func (*CreateNoteRequest) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{10}
}

func (x *CreateNoteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateNoteRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateNoteRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateNoteRequest) GetImages() []*ImageUpload {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *CreateNoteRequest) GetAudios() []*AudioUpload {
	if x != nil {
		return x.Audios
	}
	return nil
}

type CreateNoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Note          *Note                  `protobuf:"bytes,1,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNoteResponse) Reset() {
	*x = CreateNoteResponse{}
	mi := &file_proto_etu_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNoteResponse) ProtoMessage() {}

func (x *CreateNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNoteResponse.ProtoReflect.Descriptor instead.
func (*CreateNoteResponse) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{11}
}

func (x *CreateNoteResponse) GetNote() *Note {
	if x != nil {
		return x.Note
	}
	return nil
}

type GetNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Required for auth context
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNoteRequest) Reset() {
	*x = GetNoteRequest{}
	mi := &file_proto_etu_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoteRequest) ProtoMessage() {}

func (x *GetNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoteRequest.ProtoReflect.Descriptor instead.
func (*GetNoteRequest) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{12}
}

func (x *GetNoteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetNoteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetNoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Note          *Note                  `protobuf:"bytes,1,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNoteResponse) Reset() {
	*x = GetNoteResponse{}
	mi := &file_proto_etu_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoteResponse) ProtoMessage() {}

func (x *GetNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoteResponse.ProtoReflect.Descriptor instead.
func (*GetNoteResponse) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{13}
}

func (x *GetNoteResponse) GetNote() *Note {
	if x != nil {
		return x.Note
	}
	return nil
}

type UpdateNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Required for auth context
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Content       *string                `protobuf:"bytes,3,opt,name=content,proto3,oneof" json:"content,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	UpdateTags    bool                   `protobuf:"varint,5,opt,name=update_tags,json=updateTags,proto3" json:"update_tags,omitempty"` // Flag to indicate if tags should be updated
	AddImages     []*ImageUpload         `protobuf:"bytes,6,rep,name=add_images,json=addImages,proto3" json:"add_images,omitempty"`
	AddAudios     []*AudioUpload         `protobuf:"bytes,7,rep,name=add_audios,json=addAudios,proto3" json:"add_audios,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNoteRequest) Reset() {
	*x = UpdateNoteRequest{}
	mi := &file_proto_etu_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNoteRequest) ProtoMessage() {}

func (x *UpdateNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNoteRequest.ProtoReflect.Descriptor instead.
func (*UpdateNoteRequest) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateNoteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateNoteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateNoteRequest) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

func (x *UpdateNoteRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateNoteRequest) GetUpdateTags() bool {
	if x != nil {
		return x.UpdateTags
	}
	return false
}

func (x *UpdateNoteRequest) GetAddImages() []*ImageUpload {
	if x != nil {
		return x.AddImages
	}
	return nil
}

func (x *UpdateNoteRequest) GetAddAudios() []*AudioUpload {
	if x != nil {
		return x.AddAudios
	}
	return nil
}

type UpdateNoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Note          *Note                  `protobuf:"bytes,1,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNoteResponse) Reset() {
	*x = UpdateNoteResponse{}
	mi := &file_proto_etu_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNoteResponse) ProtoMessage() {}

func (x *UpdateNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNoteResponse.ProtoReflect.Descriptor instead.
func (*UpdateNoteResponse) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateNoteResponse) GetNote() *Note {
	if x != nil {
		return x.Note
	}
	return nil
}

type DeleteNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Required for auth context
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNoteRequest) Reset() {
	*x = DeleteNoteRequest{}
	mi := &file_proto_etu_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNoteRequest) ProtoMessage() {}

func (x *DeleteNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNoteRequest.ProtoReflect.Descriptor instead.
func (*DeleteNoteRequest) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteNoteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteNoteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteNoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNoteResponse) Reset() {
	*x = DeleteNoteResponse{}
	mi := &file_proto_etu_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNoteResponse) ProtoMessage() {}

func (x *DeleteNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNoteResponse.ProtoReflect.Descriptor instead.
func (*DeleteNoteResponse) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteNoteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetRandomNotesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Required for auth context
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`                // Number of random notes to return (default: 5)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRandomNotesRequest) Reset() {
	*x = GetRandomNotesRequest{}
	mi := &file_proto_etu_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRandomNotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomNotesRequest) ProtoMessage() {}

func (x *GetRandomNotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomNotesRequest.ProtoReflect.Descriptor instead.
func (*GetRandomNotesRequest) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{18}
}

func (x *GetRandomNotesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetRandomNotesRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetRandomNotesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notes         []*Note                `protobuf:"bytes,1,rep,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRandomNotesResponse) Reset() {
	*x = GetRandomNotesResponse{}
	mi := &file_proto_etu_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRandomNotesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomNotesResponse) ProtoMessage() {}

func (x *GetRandomNotesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomNotesResponse.ProtoReflect.Descriptor instead.
func (*GetRandomNotesResponse) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{19}
}

func (x *GetRandomNotesResponse) GetNotes() []*Note {
	if x != nil {
		return x.Notes
	}
	return nil
}

type ListTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Required for auth context
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagsRequest) Reset() {
	*x = ListTagsRequest{}
	mi := &file_proto_etu_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagsRequest) ProtoMessage() {}

func (x *ListTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagsRequest.ProtoReflect.Descriptor instead.
func (*ListTagsRequest) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{20}
}

func (x *ListTagsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*Tag                 `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagsResponse) Reset() {
	*x = ListTagsResponse{}
	mi := &file_proto_etu_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagsResponse) ProtoMessage() {}

func (x *ListTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagsResponse.ProtoReflect.Descriptor instead.
func (*ListTagsResponse) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{21}
}

func (x *ListTagsResponse) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_etu_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{22}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_etu_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{23}
}

func (x *RegisterResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type AuthenticateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
	mi := &file_proto_etu_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{24}
}

func (x *AuthenticateRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthenticateRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthenticateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3,oneof" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateResponse) Reset() {
	*x = AuthenticateResponse{}
	mi := &file_proto_etu_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateResponse) ProtoMessage() {}

func (x *AuthenticateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{25}
}

func (x *AuthenticateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuthenticateResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_proto_etu_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{26}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_proto_etu_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{27}
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserByStripeCustomerIdRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StripeCustomerId string                 `protobuf:"bytes,1,opt,name=stripe_customer_id,json=stripeCustomerId,proto3" json:"stripe_customer_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetUserByStripeCustomerIdRequest) Reset() {
	*x = GetUserByStripeCustomerIdRequest{}
	mi := &file_proto_etu_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByStripeCustomerIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByStripeCustomerIdRequest) ProtoMessage() {}

func (x *GetUserByStripeCustomerIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByStripeCustomerIdRequest.ProtoReflect.Descriptor instead.
func (*GetUserByStripeCustomerIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{28}
}

func (x *GetUserByStripeCustomerIdRequest) GetStripeCustomerId() string {
	if x != nil {
		return x.StripeCustomerId
	}
	return ""
}

type GetUserByStripeCustomerIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3,oneof" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByStripeCustomerIdResponse) Reset() {
	*x = GetUserByStripeCustomerIdResponse{}
	mi := &file_proto_etu_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByStripeCustomerIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByStripeCustomerIdResponse) ProtoMessage() {}

func (x *GetUserByStripeCustomerIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByStripeCustomerIdResponse.ProtoReflect.Descriptor instead.
func (*GetUserByStripeCustomerIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{29}
}

func (x *GetUserByStripeCustomerIdResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserSubscriptionRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserId             string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SubscriptionStatus string                 `protobuf:"bytes,2,opt,name=subscription_status,json=subscriptionStatus,proto3" json:"subscription_status,omitempty"`
	StripeCustomerId   *string                `protobuf:"bytes,3,opt,name=stripe_customer_id,json=stripeCustomerId,proto3,oneof" json:"stripe_customer_id,omitempty"`
	SubscriptionEnd    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=subscription_end,json=subscriptionEnd,proto3,oneof" json:"subscription_end,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateUserSubscriptionRequest) Reset() {
	*x = UpdateUserSubscriptionRequest{}
	mi := &file_proto_etu_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserSubscriptionRequest) ProtoMessage() {}

func (x *UpdateUserSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{30}
}

func (x *UpdateUserSubscriptionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserSubscriptionRequest) GetSubscriptionStatus() string {
	if x != nil {
		return x.SubscriptionStatus
	}
	return ""
}

func (x *UpdateUserSubscriptionRequest) GetStripeCustomerId() string {
	if x != nil && x.StripeCustomerId != nil {
		return *x.StripeCustomerId
	}
	return ""
}

func (x *UpdateUserSubscriptionRequest) GetSubscriptionEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.SubscriptionEnd
	}
	return nil
}

type UpdateUserSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserSubscriptionResponse) Reset() {
	*x = UpdateUserSubscriptionResponse{}
	mi := &file_proto_etu_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserSubscriptionResponse) ProtoMessage() {}

func (x *UpdateUserSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{31}
}

func (x *UpdateUserSubscriptionResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type CreateApiKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateApiKeyRequest) Reset() {
	*x = CreateApiKeyRequest{}
	mi := &file_proto_etu_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateApiKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApiKeyRequest) ProtoMessage() {}

func (x *CreateApiKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApiKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateApiKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{32}
}

func (x *CreateApiKeyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateApiKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateApiKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        *ApiKey                `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	RawKey        string                 `protobuf:"bytes,2,opt,name=raw_key,json=rawKey,proto3" json:"raw_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateApiKeyResponse) Reset() {
	*x = CreateApiKeyResponse{}
	mi := &file_proto_etu_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateApiKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApiKeyResponse) ProtoMessage() {}

func (x *CreateApiKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApiKeyResponse.ProtoReflect.Descriptor instead.
func (*CreateApiKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{33}
}

func (x *CreateApiKeyResponse) GetApiKey() *ApiKey {
	if x != nil {
		return x.ApiKey
	}
	return nil
}

func (x *CreateApiKeyResponse) GetRawKey() string {
	if x != nil {
		return x.RawKey
	}
	return ""
}

type ListApiKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApiKeysRequest) Reset() {
	*x = ListApiKeysRequest{}
	mi := &file_proto_etu_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApiKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApiKeysRequest) ProtoMessage() {}

func (x *ListApiKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApiKeysRequest.ProtoReflect.Descriptor instead.
func (*ListApiKeysRequest) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{34}
}

func (x *ListApiKeysRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListApiKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKeys       []*ApiKey              `protobuf:"bytes,1,rep,name=api_keys,json=apiKeys,proto3" json:"api_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApiKeysResponse) Reset() {
	*x = ListApiKeysResponse{}
	mi := &file_proto_etu_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApiKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApiKeysResponse) ProtoMessage() {}

func (x *ListApiKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApiKeysResponse.ProtoReflect.Descriptor instead.
func (*ListApiKeysResponse) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{35}
}

func (x *ListApiKeysResponse) GetApiKeys() []*ApiKey {
	if x != nil {
		return x.ApiKeys
	}
	return nil
}

type DeleteApiKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	KeyId         string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteApiKeyRequest) Reset() {
	*x = DeleteApiKeyRequest{}
	mi := &file_proto_etu_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteApiKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteApiKeyRequest) ProtoMessage() {}

func (x *DeleteApiKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteApiKeyRequest.ProtoReflect.Descriptor instead.
func (*DeleteApiKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{36}
}

func (x *DeleteApiKeyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteApiKeyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

type DeleteApiKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteApiKeyResponse) Reset() {
	*x = DeleteApiKeyResponse{}
	mi := &file_proto_etu_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteApiKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteApiKeyResponse) ProtoMessage() {}

func (x *DeleteApiKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteApiKeyResponse.ProtoReflect.Descriptor instead.
func (*DeleteApiKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{37}
}

func (x *DeleteApiKeyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type VerifyApiKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawKey        string                 `protobuf:"bytes,1,opt,name=raw_key,json=rawKey,proto3" json:"raw_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyApiKeyRequest) Reset() {
	*x = VerifyApiKeyRequest{}
	mi := &file_proto_etu_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyApiKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyApiKeyRequest) ProtoMessage() {}

func (x *VerifyApiKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyApiKeyRequest.ProtoReflect.Descriptor instead.
func (*VerifyApiKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{38}
}

func (x *VerifyApiKeyRequest) GetRawKey() string {
	if x != nil {
		return x.RawKey
	}
	return ""
}

type VerifyApiKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserId        *string                `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyApiKeyResponse) Reset() {
	*x = VerifyApiKeyResponse{}
	mi := &file_proto_etu_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyApiKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyApiKeyResponse) ProtoMessage() {}

func (x *VerifyApiKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyApiKeyResponse.ProtoReflect.Descriptor instead.
func (*VerifyApiKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{39}
}

func (x *VerifyApiKeyResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyApiKeyResponse) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

type GetUserSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSettingsRequest) Reset() {
	*x = GetUserSettingsRequest{}
	mi := &file_proto_etu_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSettingsRequest) ProtoMessage() {}

func (x *GetUserSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetUserSettingsRequest) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{40}
}

func (x *GetUserSettingsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSettingsResponse) Reset() {
	*x = GetUserSettingsResponse{}
	mi := &file_proto_etu_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSettingsResponse) ProtoMessage() {}

func (x *GetUserSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSettingsResponse.ProtoReflect.Descriptor instead.
func (*GetUserSettingsResponse) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{41}
}

func (x *GetUserSettingsResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NotionKey     *string                `protobuf:"bytes,2,opt,name=notion_key,json=notionKey,proto3,oneof" json:"notion_key,omitempty"`
	Name          *string                `protobuf:"bytes,4,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Image         *string                `protobuf:"bytes,5,opt,name=image,proto3,oneof" json:"image,omitempty"`
	Password      *string                `protobuf:"bytes,6,opt,name=password,proto3,oneof" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserSettingsRequest) Reset() {
	*x = UpdateUserSettingsRequest{}
	mi := &file_proto_etu_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserSettingsRequest) ProtoMessage() {}

func (x *UpdateUserSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserSettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserSettingsRequest) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{42}
}

func (x *UpdateUserSettingsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserSettingsRequest) GetNotionKey() string {
	if x != nil && x.NotionKey != nil {
		return *x.NotionKey
	}
	return ""
}

func (x *UpdateUserSettingsRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateUserSettingsRequest) GetImage() string {
	if x != nil && x.Image != nil {
		return *x.Image
	}
	return ""
}

func (x *UpdateUserSettingsRequest) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

type UpdateUserSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserSettingsResponse) Reset() {
	*x = UpdateUserSettingsResponse{}
	mi := &file_proto_etu_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserSettingsResponse) ProtoMessage() {}

func (x *UpdateUserSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserSettingsResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserSettingsResponse) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{43}
}

func (x *UpdateUserSettingsResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // If empty or omitted, returns stats for all users
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_proto_etu_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{44}
}

func (x *GetStatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalBlips    int64                  `protobuf:"varint,1,opt,name=total_blips,json=totalBlips,proto3" json:"total_blips,omitempty"`       // Total number of notes (blips)
	UniqueTags    int64                  `protobuf:"varint,2,opt,name=unique_tags,json=uniqueTags,proto3" json:"unique_tags,omitempty"`       // Number of unique tags
	WordsWritten  int64                  `protobuf:"varint,3,opt,name=words_written,json=wordsWritten,proto3" json:"words_written,omitempty"` // Total word count across all notes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_proto_etu_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etu_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_etu_proto_rawDescGZIP(), []int{45}
}

func (x *GetStatsResponse) GetTotalBlips() int64 {
	if x != nil {
		return x.TotalBlips
	}
	return 0
}

func (x *GetStatsResponse) GetUniqueTags() int64 {
	if x != nil {
		return x.UniqueTags
	}
	return 0
}

func (x *GetStatsResponse) GetWordsWritten() int64 {
	if x != nil {
		return x.WordsWritten
	}
	return 0
}

var File_proto_etu_proto protoreflect.FileDescriptor

const file_proto_etu_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/etu.proto\x12\x03etu\x1a\x1fgoogle/protobuf/timestamp.proto\">\n" +
	"\vImageUpload\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\">\n" +
	"\vAudioUpload\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\"\xac\x01\n" +
	"\tNoteImage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12%\n" +
	"\x0eextracted_text\x18\x03 \x01(\tR\rextractedText\x12\x1b\n" +
	"\tmime_type\x18\x04 \x01(\tR\bmimeType\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xb0\x01\n" +
	"\tNoteAudio\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12)\n" +
	"\x10transcribed_text\x18\x03 \x01(\tR\x0ftranscribedText\x12\x1b\n" +
	"\tmime_type\x18\x04 \x01(\tR\bmimeType\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x8a\x02\n" +
	"\x04Note\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12&\n" +
	"\x06images\x18\x06 \x03(\v2\x0e.etu.NoteImageR\x06images\x12&\n" +
	"\x06audios\x18\a \x03(\v2\x0e.etu.NoteAudioR\x06audios\"z\n" +
	"\x03Tag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xc6\x05\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x19\n" +
	"\x05image\x18\x04 \x01(\tH\x01R\x05image\x88\x01\x01\x12/\n" +
	"\x13subscription_status\x18\x05 \x01(\tR\x12subscriptionStatus\x12J\n" +
	"\x10subscription_end\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\x0fsubscriptionEnd\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x121\n" +
	"\x12stripe_customer_id\x18\b \x01(\tH\x03R\x10stripeCustomerId\x88\x01\x01\x12\"\n" +
	"\n" +
	"notion_key\x18\t \x01(\tH\x04R\tnotionKey\x88\x01\x01\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1a\n" +
	"\bdisabled\x18\f \x01(\bR\bdisabled\x12A\n" +
	"\x0fdisabled_reason\x18\r \x01(\x0e2\x13.etu.DisabledReasonH\x05R\x0edisabledReason\x88\x01\x01\x12B\n" +
	"\flocked_until\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampH\x06R\vlockedUntil\x88\x01\x01B\a\n" +
	"\x05_nameB\b\n" +
	"\x06_imageB\x13\n" +
	"\x11_subscription_endB\x15\n" +
	"\x13_stripe_customer_idB\r\n" +
	"\v_notion_keyB\x12\n" +
	"\x10_disabled_reasonB\x0f\n" +
	"\r_locked_untilJ\x04\b\n" +
	"\x10\v\"\xd2\x01\n" +
	"\x06ApiKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"key_prefix\x18\x03 \x01(\tR\tkeyPrefix\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12<\n" +
	"\tlast_used\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\blastUsed\x88\x01\x01B\f\n" +
	"\n" +
	"_last_used\"\xbf\x01\n" +
	"\x10ListNotesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06search\x18\x02 \x01(\tR\x06search\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\x1d\n" +
	"\n" +
	"start_date\x18\x04 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x05 \x01(\tR\aendDate\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\a \x01(\x05R\x06offset\"x\n" +
	"\x11ListNotesResponse\x12\x1f\n" +
	"\x05notes\x18\x01 \x03(\v2\t.etu.NoteR\x05notes\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"\xae\x01\n" +
	"\x11CreateNoteRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12(\n" +
	"\x06images\x18\x04 \x03(\v2\x10.etu.ImageUploadR\x06images\x12(\n" +
	"\x06audios\x18\x05 \x03(\v2\x10.etu.AudioUploadR\x06audios\"3\n" +
	"\x12CreateNoteResponse\x12\x1d\n" +
	"\x04note\x18\x01 \x01(\v2\t.etu.NoteR\x04note\"9\n" +
	"\x0eGetNoteRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"0\n" +
	"\x0fGetNoteResponse\x12\x1d\n" +
	"\x04note\x18\x01 \x01(\v2\t.etu.NoteR\x04note\"\xfe\x01\n" +
	"\x11UpdateNoteRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1d\n" +
	"\acontent\x18\x03 \x01(\tH\x00R\acontent\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x1f\n" +
	"\vupdate_tags\x18\x05 \x01(\bR\n" +
	"updateTags\x12/\n" +
	"\n" +
	"add_images\x18\x06 \x03(\v2\x10.etu.ImageUploadR\taddImages\x12/\n" +
	"\n" +
	"add_audios\x18\a \x03(\v2\x10.etu.AudioUploadR\taddAudiosB\n" +
	"\n" +
	"\b_content\"3\n" +
	"\x12UpdateNoteResponse\x12\x1d\n" +
	"\x04note\x18\x01 \x01(\v2\t.etu.NoteR\x04note\"<\n" +
	"\x11DeleteNoteRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\".\n" +
	"\x12DeleteNoteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"F\n" +
	"\x15GetRandomNotesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"9\n" +
	"\x16GetRandomNotesResponse\x12\x1f\n" +
	"\x05notes\x18\x01 \x03(\v2\t.etu.NoteR\x05notes\"*\n" +
	"\x0fListTagsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"0\n" +
	"\x10ListTagsResponse\x12\x1c\n" +
	"\x04tags\x18\x01 \x03(\v2\b.etu.TagR\x04tags\"C\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"1\n" +
	"\x10RegisterResponse\x12\x1d\n" +
	"\x04user\x18\x01 \x01(\v2\t.etu.UserR\x04user\"G\n" +
	"\x13AuthenticateRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"]\n" +
	"\x14AuthenticateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\"\n" +
	"\x04user\x18\x02 \x01(\v2\t.etu.UserH\x00R\x04user\x88\x01\x01B\a\n" +
	"\x05_user\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"0\n" +
	"\x0fGetUserResponse\x12\x1d\n" +
	"\x04user\x18\x01 \x01(\v2\t.etu.UserR\x04user\"P\n" +
	" GetUserByStripeCustomerIdRequest\x12,\n" +
	"\x12stripe_customer_id\x18\x01 \x01(\tR\x10stripeCustomerId\"P\n" +
	"!GetUserByStripeCustomerIdResponse\x12\"\n" +
	"\x04user\x18\x01 \x01(\v2\t.etu.UserH\x00R\x04user\x88\x01\x01B\a\n" +
	"\x05_user\"\x94\x02\n" +
	"\x1dUpdateUserSubscriptionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12/\n" +
	"\x13subscription_status\x18\x02 \x01(\tR\x12subscriptionStatus\x121\n" +
	"\x12stripe_customer_id\x18\x03 \x01(\tH\x00R\x10stripeCustomerId\x88\x01\x01\x12J\n" +
	"\x10subscription_end\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x0fsubscriptionEnd\x88\x01\x01B\x15\n" +
	"\x13_stripe_customer_idB\x13\n" +
	"\x11_subscription_end\"?\n" +
	"\x1eUpdateUserSubscriptionResponse\x12\x1d\n" +
	"\x04user\x18\x01 \x01(\v2\t.etu.UserR\x04user\"B\n" +
	"\x13CreateApiKeyRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"U\n" +
	"\x14CreateApiKeyResponse\x12$\n" +
	"\aapi_key\x18\x01 \x01(\v2\v.etu.ApiKeyR\x06apiKey\x12\x17\n" +
	"\araw_key\x18\x02 \x01(\tR\x06rawKey\"-\n" +
	"\x12ListApiKeysRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"=\n" +
	"\x13ListApiKeysResponse\x12&\n" +
	"\bapi_keys\x18\x01 \x03(\v2\v.etu.ApiKeyR\aapiKeys\"E\n" +
	"\x13DeleteApiKeyRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\"0\n" +
	"\x14DeleteApiKeyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\".\n" +
	"\x13VerifyApiKeyRequest\x12\x17\n" +
	"\araw_key\x18\x01 \x01(\tR\x06rawKey\"V\n" +
	"\x14VerifyApiKeyResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x1c\n" +
	"\auser_id\x18\x02 \x01(\tH\x00R\x06userId\x88\x01\x01B\n" +
	"\n" +
	"\b_user_id\"1\n" +
	"\x16GetUserSettingsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\">\n" +
	"\x17GetUserSettingsResponse\x12\x1d\n" +
	"\x04user\x18\x02 \x01(\v2\t.etu.UserR\x04userJ\x04\b\x01\x10\x02\"\xe2\x01\n" +
	"\x19UpdateUserSettingsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\"\n" +
	"\n" +
	"notion_key\x18\x02 \x01(\tH\x00R\tnotionKey\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x04 \x01(\tH\x01R\x04name\x88\x01\x01\x12\x19\n" +
	"\x05image\x18\x05 \x01(\tH\x02R\x05image\x88\x01\x01\x12\x1f\n" +
	"\bpassword\x18\x06 \x01(\tH\x03R\bpassword\x88\x01\x01B\r\n" +
	"\v_notion_keyB\a\n" +
	"\x05_nameB\b\n" +
	"\x06_imageB\v\n" +
	"\t_passwordJ\x04\b\x03\x10\x04\"A\n" +
	"\x1aUpdateUserSettingsResponse\x12\x1d\n" +
	"\x04user\x18\x02 \x01(\v2\t.etu.UserR\x04userJ\x04\b\x01\x10\x02\"*\n" +
	"\x0fGetStatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"y\n" +
	"\x10GetStatsResponse\x12\x1f\n" +
	"\vtotal_blips\x18\x01 \x01(\x03R\n" +
	"totalBlips\x12\x1f\n" +
	"\vunique_tags\x18\x02 \x01(\x03R\n" +
	"uniqueTags\x12#\n" +
	"\rwords_written\x18\x03 \x01(\x03R\fwordsWritten*\xdc\x01\n" +
	"\x0eDisabledReason\x12\x1f\n" +
	"\x1bDISABLED_REASON_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fDISABLED_REASON_TERMS_VIOLATION\x10\x01\x12$\n" +
	" DISABLED_REASON_SECURITY_CONCERN\x10\x02\x12 \n" +
	"\x1cDISABLED_REASON_USER_REQUEST\x10\x03\x12!\n" +
	"\x1dDISABLED_REASON_PAYMENT_ISSUE\x10\x04\x12\x19\n" +
	"\x15DISABLED_REASON_OTHER\x10\x052\x88\x03\n" +
	"\fNotesService\x12:\n" +
	"\tListNotes\x12\x15.etu.ListNotesRequest\x1a\x16.etu.ListNotesResponse\x12=\n" +
	"\n" +
	"CreateNote\x12\x16.etu.CreateNoteRequest\x1a\x17.etu.CreateNoteResponse\x124\n" +
	"\aGetNote\x12\x13.etu.GetNoteRequest\x1a\x14.etu.GetNoteResponse\x12=\n" +
	"\n" +
	"UpdateNote\x12\x16.etu.UpdateNoteRequest\x1a\x17.etu.UpdateNoteResponse\x12=\n" +
	"\n" +
	"DeleteNote\x12\x16.etu.DeleteNoteRequest\x1a\x17.etu.DeleteNoteResponse\x12I\n" +
	"\x0eGetRandomNotes\x12\x1a.etu.GetRandomNotesRequest\x1a\x1b.etu.GetRandomNotesResponse2F\n" +
	"\vTagsService\x127\n" +
	"\bListTags\x12\x14.etu.ListTagsRequest\x1a\x15.etu.ListTagsResponse2\x90\x03\n" +
	"\vAuthService\x127\n" +
	"\bRegister\x12\x14.etu.RegisterRequest\x1a\x15.etu.RegisterResponse\x12C\n" +
	"\fAuthenticate\x12\x18.etu.AuthenticateRequest\x1a\x19.etu.AuthenticateResponse\x124\n" +
	"\aGetUser\x12\x13.etu.GetUserRequest\x1a\x14.etu.GetUserResponse\x12j\n" +
	"\x19GetUserByStripeCustomerId\x12%.etu.GetUserByStripeCustomerIdRequest\x1a&.etu.GetUserByStripeCustomerIdResponse\x12a\n" +
	"\x16UpdateUserSubscription\x12\".etu.UpdateUserSubscriptionRequest\x1a#.etu.UpdateUserSubscriptionResponse2\xa1\x02\n" +
	"\x0eApiKeysService\x12C\n" +
	"\fCreateApiKey\x12\x18.etu.CreateApiKeyRequest\x1a\x19.etu.CreateApiKeyResponse\x12@\n" +
	"\vListApiKeys\x12\x17.etu.ListApiKeysRequest\x1a\x18.etu.ListApiKeysResponse\x12C\n" +
	"\fDeleteApiKey\x12\x18.etu.DeleteApiKeyRequest\x1a\x19.etu.DeleteApiKeyResponse\x12C\n" +
	"\fVerifyApiKey\x12\x18.etu.VerifyApiKeyRequest\x1a\x19.etu.VerifyApiKeyResponse2\xba\x01\n" +
	"\x13UserSettingsService\x12L\n" +
	"\x0fGetUserSettings\x12\x1b.etu.GetUserSettingsRequest\x1a\x1c.etu.GetUserSettingsResponse\x12U\n" +
	"\x12UpdateUserSettings\x12\x1e.etu.UpdateUserSettingsRequest\x1a\x1f.etu.UpdateUserSettingsResponse2G\n" +
	"\fStatsService\x127\n" +
	"\bGetStats\x12\x14.etu.GetStatsRequest\x1a\x15.etu.GetStatsResponseB#Z!github.com/icco/etu-backend/protob\x06proto3"

var (
	file_proto_etu_proto_rawDescOnce sync.Once
	file_proto_etu_proto_rawDescData []byte
)

func file_proto_etu_proto_rawDescGZIP() []byte {
	file_proto_etu_proto_rawDescOnce.Do(func() {
		file_proto_etu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_etu_proto_rawDesc), len(file_proto_etu_proto_rawDesc)))
	})
	return file_proto_etu_proto_rawDescData
}

var file_proto_etu_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_etu_proto_msgTypes = make([]protoimpl.MessageInfo, 46)
var file_proto_etu_proto_goTypes = []any{
	(DisabledReason)(0),                       // 0: etu.DisabledReason
	(*ImageUpload)(nil),                       // 1: etu.ImageUpload
	(*AudioUpload)(nil),                       // 2: etu.AudioUpload
	(*NoteImage)(nil),                         // 3: etu.NoteImage
	(*NoteAudio)(nil),                         // 4: etu.NoteAudio
	(*Note)(nil),                              // 5: etu.Note
	(*Tag)(nil),                               // 6: etu.Tag
	(*User)(nil),                              // 7: etu.User
	(*ApiKey)(nil),                            // 8: etu.ApiKey
	(*ListNotesRequest)(nil),                  // 9: etu.ListNotesRequest
	(*ListNotesResponse)(nil),                 // 10: etu.ListNotesResponse
	(*CreateNoteRequest)(nil),                 // 11: etu.CreateNoteRequest
	(*CreateNoteResponse)(nil),                // 12: etu.CreateNoteResponse
	(*GetNoteRequest)(nil),                    // 13: etu.GetNoteRequest
	(*GetNoteResponse)(nil),                   // 14: etu.GetNoteResponse
	(*UpdateNoteRequest)(nil),                 // 15: etu.UpdateNoteRequest
	(*UpdateNoteResponse)(nil),                // 16: etu.UpdateNoteResponse
	(*DeleteNoteRequest)(nil),                 // 17: etu.DeleteNoteRequest
	(*DeleteNoteResponse)(nil),                // 18: etu.DeleteNoteResponse
	(*GetRandomNotesRequest)(nil),             // 19: etu.GetRandomNotesRequest
	(*GetRandomNotesResponse)(nil),            // 20: etu.GetRandomNotesResponse
	(*ListTagsRequest)(nil),                   // 21: etu.ListTagsRequest
	(*ListTagsResponse)(nil),                  // 22: etu.ListTagsResponse
	(*RegisterRequest)(nil),                   // 23: etu.RegisterRequest
	(*RegisterResponse)(nil),                  // 24: etu.RegisterResponse
	(*AuthenticateRequest)(nil),               // 25: etu.AuthenticateRequest
	(*AuthenticateResponse)(nil),              // 26: etu.AuthenticateResponse
	(*GetUserRequest)(nil),                    // 27: etu.GetUserRequest
	(*GetUserResponse)(nil),                   // 28: etu.GetUserResponse
	(*GetUserByStripeCustomerIdRequest)(nil),  // 29: etu.GetUserByStripeCustomerIdRequest
	(*GetUserByStripeCustomerIdResponse)(nil), // 30: etu.GetUserByStripeCustomerIdResponse
	(*UpdateUserSubscriptionRequest)(nil),     // 31: etu.UpdateUserSubscriptionRequest
	(*UpdateUserSubscriptionResponse)(nil),    // 32: etu.UpdateUserSubscriptionResponse
	(*CreateApiKeyRequest)(nil),               // 33: etu.CreateApiKeyRequest
	(*CreateApiKeyResponse)(nil),              // 34: etu.CreateApiKeyResponse
	(*ListApiKeysRequest)(nil),                // 35: etu.ListApiKeysRequest
	(*ListApiKeysResponse)(nil),               // 36: etu.ListApiKeysResponse
	(*DeleteApiKeyRequest)(nil),               // 37: etu.DeleteApiKeyRequest
	(*DeleteApiKeyResponse)(nil),              // 38: etu.DeleteApiKeyResponse
	(*VerifyApiKeyRequest)(nil),               // 39: etu.VerifyApiKeyRequest
	(*VerifyApiKeyResponse)(nil),              // 40: etu.VerifyApiKeyResponse
	(*GetUserSettingsRequest)(nil),            // 41: etu.GetUserSettingsRequest
	(*GetUserSettingsResponse)(nil),           // 42: etu.GetUserSettingsResponse
	(*UpdateUserSettingsRequest)(nil),         // 43: etu.UpdateUserSettingsRequest
	(*UpdateUserSettingsResponse)(nil),        // 44: etu.UpdateUserSettingsResponse
	(*GetStatsRequest)(nil),                   // 45: etu.GetStatsRequest
	(*GetStatsResponse)(nil),                  // 46: etu.GetStatsResponse
	(*timestamppb.Timestamp)(nil),             // 47: google.protobuf.Timestamp
}
var file_proto_etu_proto_depIdxs = []int32{
	47, // 0: etu.NoteImage.created_at:type_name -> google.protobuf.Timestamp
	47, // 1: etu.NoteAudio.created_at:type_name -> google.protobuf.Timestamp
	47, // 2: etu.Note.created_at:type_name -> google.protobuf.Timestamp
	47, // 3: etu.Note.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 4: etu.Note.images:type_name -> etu.NoteImage
	4,  // 5: etu.Note.audios:type_name -> etu.NoteAudio
	47, // 6: etu.Tag.created_at:type_name -> google.protobuf.Timestamp
	47, // 7: etu.User.subscription_end:type_name -> google.protobuf.Timestamp
	47, // 8: etu.User.created_at:type_name -> google.protobuf.Timestamp
	47, // 9: etu.User.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 10: etu.User.disabled_reason:type_name -> etu.DisabledReason
	47, // 11: etu.User.locked_until:type_name -> google.protobuf.Timestamp
	47, // 12: etu.ApiKey.created_at:type_name -> google.protobuf.Timestamp
	47, // 13: etu.ApiKey.last_used:type_name -> google.protobuf.Timestamp
	5,  // 14: etu.ListNotesResponse.notes:type_name -> etu.Note
	1,  // 15: etu.CreateNoteRequest.images:type_name -> etu.ImageUpload
	2,  // 16: etu.CreateNoteRequest.audios:type_name -> etu.AudioUpload
	5,  // 17: etu.CreateNoteResponse.note:type_name -> etu.Note
	5,  // 18: etu.GetNoteResponse.note:type_name -> etu.Note
	1,  // 19: etu.UpdateNoteRequest.add_images:type_name -> etu.ImageUpload
	2,  // 20: etu.UpdateNoteRequest.add_audios:type_name -> etu.AudioUpload
	5,  // 21: etu.UpdateNoteResponse.note:type_name -> etu.Note
	5,  // 22: etu.GetRandomNotesResponse.notes:type_name -> etu.Note
	6,  // 23: etu.ListTagsResponse.tags:type_name -> etu.Tag
	7,  // 24: etu.RegisterResponse.user:type_name -> etu.User
	7,  // 25: etu.AuthenticateResponse.user:type_name -> etu.User
	7,  // 26: etu.GetUserResponse.user:type_name -> etu.User
	7,  // 27: etu.GetUserByStripeCustomerIdResponse.user:type_name -> etu.User
	47, // 28: etu.UpdateUserSubscriptionRequest.subscription_end:type_name -> google.protobuf.Timestamp
	7,  // 29: etu.UpdateUserSubscriptionResponse.user:type_name -> etu.User
	8,  // 30: etu.CreateApiKeyResponse.api_key:type_name -> etu.ApiKey
	8,  // 31: etu.ListApiKeysResponse.api_keys:type_name -> etu.ApiKey
	7,  // 32: etu.GetUserSettingsResponse.user:type_name -> etu.User
	7,  // 33: etu.UpdateUserSettingsResponse.user:type_name -> etu.User
	9,  // 34: etu.NotesService.ListNotes:input_type -> etu.ListNotesRequest
	11, // 35: etu.NotesService.CreateNote:input_type -> etu.CreateNoteRequest
	13, // 36: etu.NotesService.GetNote:input_type -> etu.GetNoteRequest
	15, // 37: etu.NotesService.UpdateNote:input_type -> etu.UpdateNoteRequest
	17, // 38: etu.NotesService.DeleteNote:input_type -> etu.DeleteNoteRequest
	19, // 39: etu.NotesService.GetRandomNotes:input_type -> etu.GetRandomNotesRequest
	21, // 40: etu.TagsService.ListTags:input_type -> etu.ListTagsRequest
	23, // 41: etu.AuthService.Register:input_type -> etu.RegisterRequest
	25, // 42: etu.AuthService.Authenticate:input_type -> etu.AuthenticateRequest
	27, // 43: etu.AuthService.GetUser:input_type -> etu.GetUserRequest
	29, // 44: etu.AuthService.GetUserByStripeCustomerId:input_type -> etu.GetUserByStripeCustomerIdRequest
	31, // 45: etu.AuthService.UpdateUserSubscription:input_type -> etu.UpdateUserSubscriptionRequest
	33, // 46: etu.ApiKeysService.CreateApiKey:input_type -> etu.CreateApiKeyRequest
	35, // 47: etu.ApiKeysService.ListApiKeys:input_type -> etu.ListApiKeysRequest
	37, // 48: etu.ApiKeysService.DeleteApiKey:input_type -> etu.DeleteApiKeyRequest
	39, // 49: etu.ApiKeysService.VerifyApiKey:input_type -> etu.VerifyApiKeyRequest
	41, // 50: etu.UserSettingsService.GetUserSettings:input_type -> etu.GetUserSettingsRequest
	43, // 51: etu.UserSettingsService.UpdateUserSettings:input_type -> etu.UpdateUserSettingsRequest
	45, // 52: etu.StatsService.GetStats:input_type -> etu.GetStatsRequest
	10, // 53: etu.NotesService.ListNotes:output_type -> etu.ListNotesResponse
	12, // 54: etu.NotesService.CreateNote:output_type -> etu.CreateNoteResponse
	14, // 55: etu.NotesService.GetNote:output_type -> etu.GetNoteResponse
	16, // 56: etu.NotesService.UpdateNote:output_type -> etu.UpdateNoteResponse
	18, // 57: etu.NotesService.DeleteNote:output_type -> etu.DeleteNoteResponse
	20, // 58: etu.NotesService.GetRandomNotes:output_type -> etu.GetRandomNotesResponse
	22, // 59: etu.TagsService.ListTags:output_type -> etu.ListTagsResponse
	24, // 60: etu.AuthService.Register:output_type -> etu.RegisterResponse
	26, // 61: etu.AuthService.Authenticate:output_type -> etu.AuthenticateResponse
	28, // 62: etu.AuthService.GetUser:output_type -> etu.GetUserResponse
	30, // 63: etu.AuthService.GetUserByStripeCustomerId:output_type -> etu.GetUserByStripeCustomerIdResponse
	32, // 64: etu.AuthService.UpdateUserSubscription:output_type -> etu.UpdateUserSubscriptionResponse
	34, // 65: etu.ApiKeysService.CreateApiKey:output_type -> etu.CreateApiKeyResponse
	36, // 66: etu.ApiKeysService.ListApiKeys:output_type -> etu.ListApiKeysResponse
	38, // 67: etu.ApiKeysService.DeleteApiKey:output_type -> etu.DeleteApiKeyResponse
	40, // 68: etu.ApiKeysService.VerifyApiKey:output_type -> etu.VerifyApiKeyResponse
	42, // 69: etu.UserSettingsService.GetUserSettings:output_type -> etu.GetUserSettingsResponse
	44, // 70: etu.UserSettingsService.UpdateUserSettings:output_type -> etu.UpdateUserSettingsResponse
	46, // 71: etu.StatsService.GetStats:output_type -> etu.GetStatsResponse
	53, // [53:72] is the sub-list for method output_type
	34, // [34:53] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_proto_etu_proto_init() }
func file_proto_etu_proto_init() {
	if File_proto_etu_proto != nil {
		return
	}
	file_proto_etu_proto_msgTypes[6].OneofWrappers = []any{}
	file_proto_etu_proto_msgTypes[7].OneofWrappers = []any{}
	file_proto_etu_proto_msgTypes[14].OneofWrappers = []any{}
	file_proto_etu_proto_msgTypes[25].OneofWrappers = []any{}
	file_proto_etu_proto_msgTypes[29].OneofWrappers = []any{}
	file_proto_etu_proto_msgTypes[30].OneofWrappers = []any{}
	file_proto_etu_proto_msgTypes[39].OneofWrappers = []any{}
	file_proto_etu_proto_msgTypes[42].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_etu_proto_rawDesc), len(file_proto_etu_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   46,
			NumExtensions: 0,
			NumServices:   6,
		},
		GoTypes:           file_proto_etu_proto_goTypes,
		DependencyIndexes: file_proto_etu_proto_depIdxs,
		EnumInfos:         file_proto_etu_proto_enumTypes,
		MessageInfos:      file_proto_etu_proto_msgTypes,
	}.Build()
	File_proto_etu_proto = out.File
	file_proto_etu_proto_goTypes = nil
	file_proto_etu_proto_depIdxs = nil
}
