package db

const (
	colCreatedAt            = "createdAt"
	colUpdatedAt            = "updatedAt"
	colDisabled             = "disabled"
	colEmail                = "email"
	colCount                = "count"
	colContent              = "content"
	colExternalID           = "externalId"
	colExtractedText        = "extractedText"
	colTranscribedText      = "transcribedText"
	colPasswordHash         = "passwordHash"
	colFailedLoginAttempts  = "failedLoginAttempts"
	colLastFailedLogin      = "lastFailedLogin"
	colSubscriptionStatus   = "subscriptionStatus"
	colNotionKey            = "notionKey"
	colLastSyncedToNotion   = "lastSyncedToNotion"
	colGCSObjectName        = "gcsObjectName"
	colUserID               = "userId"
	colName                 = "name"
	colStripeCustomerID     = "stripeCustomerId"
	colStripeSubscriptionID = "stripeSubscriptionId"
	colStripePriceID        = "stripePriceId"
	colCancelAtPeriodEnd    = "cancelAtPeriodEnd"
	colCurrentPeriodStart   = "currentPeriodStart"
	colBillingLine1         = "billingLine1"
	colBillingLine2         = "billingLine2"
	colBillingCity          = "billingCity"
	colBillingState         = "billingState"
	colBillingPostalCode    = "billingPostalCode"
	colBillingCountry       = "billingCountry"
	colNotionUUID           = "notionUuid"
	colMimeType             = "mimeType"
	colSubscriptionEnd      = "subscriptionEnd"
	colNoteID               = "noteId"
	colURL                  = "url"

	tagWork  = "work"
	tagValid = "valid"
)
